# Numpy

**NumPy** is a popular Python library for numerical and scientific computing, and it provides a powerful data structure called a NumPy array (also known as `ndarray`) for efficiently working with large datasets of homogeneous data types, such as numbers (integers or floats). 

In [ ]:
import numpy as np

## 1. Introduction of Numpy array

### 1.1. What is an array?

A NumPy array (also known as ndarray) is a fundamental data structure provided by the NumPy library in Python. It is a multidimensional, homogeneous, and efficient array-like container that can store elements of the same data type. NumPy arrays are used extensively in scientific computing, data analysis, and numerical computing tasks.

You should consider using NumPy arrays when:

- Numerical Computations: NumPy is designed for numerical and scientific computing tasks. If you're working with numerical data, matrices, or multidimensional arrays, NumPy provides efficient tools and functions for operations like addition, subtraction, multiplication, and more.

- Large Datasets: NumPy arrays are memory-efficient and can handle large datasets without consuming excessive memory.

- Mathematical Operations: NumPy simplifies mathematical operations and vectorized computations. It allows you to apply mathematical functions element-wise to arrays, eliminating the need for explicit loops.

- Data Analysis and Statistics: NumPy is an essential component of the data science and machine learning ecosystem in Python. Many other libraries (e.g., Pandas, SciPy, scikit-learn) rely on NumPy arrays for data manipulation and analysis.

- Image and Signal Processing: NumPy is widely used for image and signal processing tasks due to its ability to handle multidimensional data.

- Machine Learning: NumPy arrays are the preferred data structure for machine learning algorithms in libraries like scikit-learn and TensorFlow.

- Simulation and Modeling: Scientists and engineers use NumPy for simulating physical systems, modeling data, and solving differential equations.

### 1.2. Why Numpy array?

NumPy arrays and Python lists are both used to store collections of data, but they have significant differences in terms of functionality and performance.

**NumPy Array:**

1. **Homogeneous Data Type:** NumPy arrays are designed to work with homogeneous data types, which means all elements in the array are of the same data type (e.g., integers, floats). This leads to more efficient memory usage and better performance.

2. **Vectorized Operations:** NumPy provides a wide range of mathematical and logical functions that can be applied element-wise to entire arrays, allowing for efficient and concise code for numerical computations. This is known as vectorization.

3. **Performance:** NumPy operations are implemented in C and are highly optimized, making them significantly faster than equivalent operations on Python lists, especially for large datasets.

4. **Memory Efficiency:** NumPy arrays are more memory-efficient than Python lists because they don't need to store type information for each element.

5. **Multidimensional Arrays:** NumPy supports multidimensional arrays (e.g., matrices), making it well-suited for mathematical and scientific applications.

6. **Broadcasting:** NumPy allows you to perform operations on arrays of different shapes through broadcasting, which simplifies many array operations.

**Python List:**

1. **Heterogeneous Data Type:** Python lists can contain elements of different data types, which provides flexibility but can lead to performance issues for numerical computations.

2. **No Built-in Mathematical Operations:** Python lists don't offer built-in mathematical or array operations. You need to loop through lists to perform operations on individual elements, which can be slower and less concise.

3. **Performance:** Python lists are generally slower than NumPy arrays, especially for large datasets and numerical operations.

4. **Memory Overhead:** Python lists have higher memory overhead due to the need to store type information for each element.

5. **Single-Dimensional:** Lists in Python are primarily single-dimensional. To work with multidimensional data, you'd need to use nested lists, which can become complex to manage.

**Why Use NumPy Arrays:**

NumPy arrays are preferred for several reasons:

1. **Performance:** NumPy operations are highly optimized and execute much faster than equivalent Python list operations, making it the go-to choice for numerical computations and data manipulation.

2. **Memory Efficiency:** NumPy arrays are more memory-efficient, especially for large datasets, due to their homogeneous data type and reduced type information overhead.

3. **Ease of Use:** NumPy provides a rich set of functions for array manipulation, statistical analysis, and linear algebra, making it easier to work with data.

4. **Compatibility:** NumPy arrays can be seamlessly integrated with other libraries and tools commonly used in scientific computing and data analysis, such as SciPy, pandas, and scikit-learn.

In [ ]:
# my_arr = np.arange(1_000_000)
# my_list = list(range(1_000_000))

# print("Numpy Array:")
# %timeit my_arr2 = my_arr * 2

# print("List:")
# %timeit my_list2 = [x * 2 for x in my_list]

### 1.3. Array creation

- Basic creation

In [ ]:
my_array = np.array((1,2,3,4))

print(my_array)
print(len(my_array))
print(my_array[0], my_array[-1])
print(my_array.dtype)

- Create an array with `dtype` specified

In [ ]:
my_array = np.array((1,2,3,4), dtype=np.int8)

print(my_array)
print(my_array.dtype)

In [ ]:
my_array = np.array((1,2,3,4)).astype(np.int8)

print(my_array)
print(my_array.dtype)

In [ ]:
# What if there are different types of data?
my_array = np.array((1,2,3,"4"))

print(my_array)
print(my_array.dtype)

- Create arrays and fill with values

In [ ]:
# Fill with zeros
my_array = np.zeros((2,3))
print("my_array")
print(my_array)
print(my_array.dtype)
print(len(my_array))
print("")

print("my_array2")
my_array2 = np.zeros_like(my_array).astype(np.int8)
print(my_array2)
print(my_array2.dtype)
print(len(my_array2))

In [ ]:
# Create a length-10 integer array filled with zeros/ones
my_array = np.zeros((2,3))
print("my_array")
print(my_array)
print(my_array.dtype)
print(len(my_array))
print("")

print("my_array2")
my_array2 = np.zeros_like(my_array).astype(np.int8)
print(my_array2)
print(my_array2.dtype)
print(len(my_array2))

In [ ]:
# Fill with ones
my_array = np.ones((2,3), dtype=np.int8)
print("my_array")
print(my_array)
print(my_array.dtype)
print(len(my_array))
print("")

print("my_array2")
my_array2 = np.ones_like(my_array)
print(my_array2)
print(my_array2.dtype)
print(len(my_array2))

In [ ]:
# Fill with custom values
my_array = np.full(shape=(3,5), fill_value=3.14, dtype=np.float16)
print("my_array")
print(my_array)
print(my_array.dtype)
print("")

my_array2 = np.full_like(my_array, fill_value=1.43, dtype=np.float32)

print(my_array2)
print(my_array2.dtype)

- Create arrays from a sequence

In [ ]:
# Create an array filled with a linear sequence
# starting at 6, ending at 49, stepping by 2
# (this is similar to the built-in range() function)
np.arange(start=6, stop=49, step=2)

In [ ]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(start=0, stop=1, num=5)

- Create arrays and fill with random values

In [ ]:
# Create a 5x5 array of uniformly distributed random values between 0 and 1
np.random.random(size=(5,5))

In [ ]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1

np.random.normal(loc=0.0, scale=1.0, size=(3,3))

## 2. Attributes of arrays

### 2.1. Size, shape, memory consumption, and data types of arrays

- The `shape` attribute is a tuple that describes the dimensions of the array. For a 1D array, it's a tuple with a single element representing the number of elements. For a 2D array, it's a tuple with two elements representing the number of rows and columns, and so on.
- The `dtype` attribute specifies the data type of the elements in the array, such as int64, float32, etc.
- The `ndim` attribute indicates the number of dimensions (axes) in the array.
- The `size` attribute represents the total number of elements in the array.
- The `itemsize` attribute specifies the size (in bytes) of each element in the array.
- The `nbytes` attribute returns the total number of bytes used by the array's data.

In [ ]:
my_array = np.array(
    [
        [[1,2], [2,3], [3,4]],
        [[4,5], [5,6], [6,7]]
    ],
    dtype=np.int8
)
print(f"Shape of array: {my_array.shape}")
print(f"Type of elements: {my_array.dtype}")
print(f"Number of dimentions: {my_array.ndim}")
print(f"Number of elements: {my_array.size}") 
print(f"Item's size: {my_array.itemsize}")
print(f"Total number of bytes used by my_array: {my_array.nbytes}")

### 2.2. Indexing & Slicing

- 1D array: similar to List indexing and slicing

In [ ]:
my_array = np.array([5,6,7,8])
print(my_array[2])
print(my_array[-1])
print(my_array[:3])
print(my_array[1:])
print(my_array[::2])

- 2D array: using a comma-separated tuple of indices

![np_matrix_indexing](img/np_matrix_indexing.png)

In [ ]:
my_array = np.array(
    [
# column 0  1  2  3
        [3, 5, 2, 4], # row 0
        [7, 6, 8, 8], # row 1
        [1, 6, 7, 99] # row 2
    ]
)

print(my_array.shape)
print(my_array[0,0])
print(my_array[-1,-1])

In [ ]:
my_array = np.array(
    [
    # cl 0  1  2  3
        [3, 5, 2, 4], # row 0
        [7, 6, 8, 8], # row 1
        [1, 6, 7, 99] # row 2
    ]
)

# Get values from the first 2 rows last column
print(my_array[:2, -1])

# Get values of every even rows and odd column
print(my_array[::2, 1::2])

- Modify values using index notation

In [ ]:
my_array = np.array(
    [
        [3, 5, 2, 4],
        [7, 6, 8, 8],
        [1, 6, 7, 99]
    ]
)
my_array[0,0] = 100

print(my_array)

**NOTE**

Numpy array slicing returns **views** rather than **copies** of the array data. In lists, slices will be copies. 

In [ ]:
my_list = [1,2,3]
copied_list = my_list[:]
copied_list[0] = 8 # only affect copied_list
print(f"my_list: {my_list}")
print(f"copied_list: {copied_list}")

In [ ]:
my_array = np.array([1,2,3])
viewed_array = my_array[:] # slicing
my_array[0] = 8 # update viewed_array as well

print(f"my_array: {my_array}")
print(f"viewed_array: {viewed_array}")

In [ ]:
my_array = np.array([1,2,3])
viewed_array = my_array[:] # slicing
viewed_array[0] = 99 # update my_array as well

print(f"my_array: {my_array}")
print(f"viewed_array: {viewed_array}")

To copy a Numpy array, use method `copy()`

In [ ]:
my_array = np.array([1,2,3,4,5,6])
copied_array = my_array.copy() # copy
copied_array[0] = 8 # only affect copied_array

print(f"my_array: {my_array}")
print(f"copied_array: {copied_array}")

It's useful when working with large datasets, we only view and copy a small piece of data instead of copying the whole dataset.

**EXERCISE**

1. Create these following matrices using Numpy arrays, be careful with the data type.

a. 
```python
[
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0]
]
```

b.
```python
[
    [1, 1, 1, 1, 1],
    [0, 0, 0, 0, 0],
    [1, 1, 1, 1, 1],
    [0, 0, 0, 0, 0],
    [1, 1, 1, 1, 1]
]
```

c.
```python
[
    [1, 0, 1, 0, 1],
    [0, 0, 0, 0, 0],
    [1, 0, 1, 0, 1],
    [0, 0, 0, 0, 0],
    [1, 0, 1, 0, 1]
]
```

2. Get all number 9 from these following arrays

a.
```python
[
    [1., 1., 1.],
    [1., 9., 1.],
    [1., 1., 1.]
]
```

b.
```python
[
    [1., 1., 1., 1.],
    [1., 1., 1., 1.],
    [9., 9., 9., 1.],
    [9., 9., 9., 1.]
]
```

c.
```python
[
    [1., 1., 1., 1., 1., 1.],
    [1., 1., 1., 1., 1., 1.],
    [1., 1., 9., 9., 1., 1.],
    [1., 1., 9., 9., 1., 1.],
    [1., 1., 1., 1., 1., 1.],
    [1., 1., 1., 1., 1., 1.]
]
```

## 3. Array manipulations

### 3.1. Reshape an array

In [ ]:
my_array = np.arange(1,17)
reshaped = my_array.reshape((4,4))

print(my_array)
print(reshaped)

### 3.2. 1D array to 2D array

![New axis](img/numpy_reshape.png)

In [ ]:
# Using reshape()
my_1d = np.array([2,0,1,8])
print(my_1d.shape, my_1d.ndim)

my_2d_row = my_1d.reshape(1, 4) # 1 row, 4 columns
print(my_2d_row.shape, my_2d_row.ndim)

my_2d_col = my_1d.reshape(4, 1) # 4 rows, 1 column
print(my_2d_col.shape, my_2d_col.ndim)

print("")
print("my_1d")
print(my_1d)
print("my_2d_row")
print(my_2d_row)
print("my_2d_col")
print(my_2d_col)

In [ ]:
# Using np.newaxis
my_1d = np.array([2,0,1,8])
print(my_1d.shape, my_1d.ndim)

my_2d_row = my_1d[np.newaxis, :]
print(my_2d_row.shape, my_2d_row.ndim)

my_2d_col = my_1d[:, np.newaxis]
print(my_2d_col.shape, my_2d_col.ndim)

print("")
print("my_1d")
print(my_1d)
print("my_2d_row")
print(my_2d_row)
print("my_2d_col")
print(my_2d_col)

In [ ]:
# Using np.expand_dims()
my_1d = np.array([2,0,1,8])
print(my_1d.shape, my_1d.ndim)

my_2d_row = np.expand_dims(my_1d, axis=0)
print(my_2d_row.shape, my_2d_row.ndim)

my_2d_col = np.expand_dims(my_1d, axis=1)
print(my_2d_col.shape, my_2d_col.ndim)

print("")
print("my_1d")
print(my_1d)
print("my_2d_row")
print(my_2d_row)
print("my_2d_col")
print(my_2d_col)

**EXERCISE**

Given an image as a Numpy array of shape (5,5,3), representing image's width and height of 5 pixels and 3 channels: Red, Green, Blue. Write a `preprocess()` function to process image with the following steps:

1. Make a copy of the input image so that changes won't affect original data.
2. Crop the copied image to the center so that the final result is 3x3x3 (get center values only)
3. This image will be fed into a deep learning model, which requires another dimension for batch. Therefore, you need to add 1 dimension to the image so that the final shape is (1,3,3,3)
3. Return the processed image

In [ ]:
# YOUR CODE

### 3.3. Reverse an array

- Using `np.flip()`

In [ ]:
my_array = np.array([3, 1, 2])
print(np.flip(my_array))

- Using `array[::-1]` syntax

In [ ]:
my_array = np.array([3, 1, 2])
print(my_array[::-1])

- Reverse along a Specific Axis (for Multi-Dimensional Arrays)

In [ ]:
# Reverse along rows
my_array = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)
print(my_array[::-1, :])
print(np.flip(my_array, axis=0))

In [ ]:
# Reverse along columns
my_array = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)
print(my_array[:, ::-1])
print(np.flip(my_array, axis=1))

In [ ]:
# Reverse along both rows and columns
my_array = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)
print(my_array[::-1, ::-1])
print(np.flip(my_array, axis=(0,1)))

### 3.4. Adding, removing, and sorting elements

### Sorting

- Using `np.sort()`

In [ ]:
my_array = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(my_array)) # return a copy of a sorted array
print(my_array)

- Using method `sort()`

In [ ]:
my_array = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(my_array.sort()) # return None
print(my_array)

- Sort with descending order

In [ ]:
# Sort then reverse
my_array = np.array([2, 1, 5, 3, 7, 4, 6, 8])
sorted_array = np.sort(my_array)
sorted_array = np.flip(sorted_array)

print(sorted_array)

In [ ]:
# Sorting Along a Specific Axis (for Multi-Dimensional Arrays)
my_array = np.array(
    [
        [4, 5, 6],
        [1, 2, 3],
        [7, 8, 9]
    ]
)
print(np.sort(my_array, axis=0))

In [ ]:
my_array = np.array(
    [
        [5, 4, 6],
        [3, 2, 1],
        [8, 7, 9]
    ]
)
print(np.sort(my_array, axis=1))

### 3.5. Numpy axes

![Numpy axes](img/numpy-arrays-have-axes_updated_v2.png)

It’s very important to understand what the `axis` parameter actually controls for each function.

- The `axis` in the `np.sum()` controls which axis will be collapsed.

In [ ]:
my_array = np.arange(0,6).reshape(2,3)
print(my_array)
print(np.sum(my_array))

![numpy-axes-np-sum-axis-0](img/numpy-axes-np-sum-axis-0.png)
![numpy-axes-np-sum-axis-1](img/numpy-axes-np-sum-axis-1.png)

In [ ]:
print("axis=0", np.sum(my_array, axis=0)) # does not sum elements along the rows, but sum elements along the columns to collapse the rows
print("axis=1", np.sum(my_array, axis=1)) # does not sum elements along the columns, but sum elements along the rows to collapse the columns

- The `axis` parameter in `np.concatenate()` controls which axis we stack the arrays.

In [ ]:
arr1 = np.ones(shape=(2,3), dtype=np.int8)
print("arr1")
print(arr1)

arr2 = np.full(shape=(2,3), fill_value=9, dtype=np.int8)
print("arr2")
print(arr2)

print("axis=0")
print(np.concatenate([arr1, arr2], axis=0))

print("axis=1")
print(np.concatenate([arr1, arr2], axis=1))

![explanation_numpy-concatenate-axis-0](img/explanation_numpy-concatenate-axis-0.png)
![explanation_numpy-concatenate-axis-1](img/explanation_numpy-concatenate-axis-1.png)

- 1D array only has 1 axis
![1d-array-has-one-axis](img/1d-array-has-one-axis.webp)

In [ ]:
arr1 = np.ones(shape=(3,), dtype=np.int8)
print(arr1)

arr2 = np.full_like(arr1, fill_value=9, dtype=np.int8)
print(arr2)

print(np.concatenate([arr1, arr2], axis=0))
#print(np.concatenate([arr1, arr2], axis=1)) # AxisError

In [ ]:
# To stack 2 1D arrays vertically
print(np.concatenate([arr1, arr2]).reshape(2,3))

## 4. Basic array operations

### 4.1. Add, subtract, multiply, divide

![np_array_dataones](img/np_array_dataones.png)
![np_data_plus_ones](img/np_data_plus_ones.png)
![np_sub_mult_divide](img/np_sub_mult_divide.png)

### 4.2. Maximum, minimum, sum, mean, product, standard deviation

![np_aggregation](img/np_aggregation.png)

**EXERCISE**

1. Create a 1D array and sum all its elements, then find the max, min values.

2. Create a 2D array and sum all elements, find the max, min values along rows.

3. Create a 2D array and sum all elements, find the max, min, values along columns.

4. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

```
Expected Output:
[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]
```

5. Write a NumPy program to reverse an array (the first element becomes the last).
```
Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]
```



### 4.2. Working with mathematical formulas

## 5. Broadcasting

## 6. Save and load Numpy objects

# REFERENCES

1. [Numpy Tutorials for Beginners](https://www.kaggle.com/code/orhansertkaya/numpy-tutorial-for-beginners)
2. [Numpy Docs](https://numpy.org/doc/stable/user/absolute_beginners.html#)
3. [Numpy Axes Explained](https://www.sharpsightlabs.com/blog/numpy-axes-explained/)